version: '3.3'

services:
    motioneyes:
      image: ccrisan/motioneye:master-amd64
      volumes:
        - /path/to/home_dir/conf:/etc/motioneye
        - /path/to/home_dir/data:/var/lib/motioneye
      restart: always
      ports:
        - 8765:8765
      network_mode: "host"
      logging:
        driver: "json-file"
        options:
          max-file: "2"
          max-size: "100m"
