version: '3.3'

services:
    motioneye:
      image: ccrisan/motioneye:master-amd64
      container_name: motioneye
      volumes:
        - ${CONF_DIR}:/etc/motioneye
        - ${DATA_DIR}:/var/lib/motioneye
      restart: always
      ports:
        - ${PORT}:8765
      network_mode: "host"
      logging:
        driver: "json-file"
        options:
          max-file: "2"
          max-size: "100m"
