version: '3.3'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    environment:
      TZ: 'Europe/Paris'
      WEBSOCKET_ENABLED: "true"
      DOMAIN: ${DOMAIN}
      ADMIN_TOKEN: '${ADMIN_TOKEN}'
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SECURITY: ${SMTP_SECURITY}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: '${SMTP_PASSWORD}'
      SMTP_FROM: ${SMTP_FROM}
    volumes:
      - ${DATA_DIR}:/data
      - /etc/localtime:/etc/localtime:ro
    network_mode: "bridge"
    ports:
      - "${PORT}:80"
