version: '3.3'

services:
    mosquitto:
      image: eclipse-mosquitto:latest
      volumes:
        - ${HOME_DIR}/data:/mosquitto/data
        - ${HOME_DIR}/config:/mosquitto/config
        - ${HOME_DIR}/log:/mosquitto/log
      restart: always
      ports:
        - 1883:1883
      logging:
        driver: "json-file"
        options:
          max-file: "2"
          max-size: "100m"

