version: '3.3'

services:
    nginx:
      image: nginx:latest
      volumes:
        - /path/to/home_dir:/etc/nginx/conf.d
        - /path/to/cert_dir:/etc/letsencrypt
      restart: always
      ports:
        - 8443:443
      logging:
        driver: "json-file"
        options:
          max-file: "2"
          max-size: "100m"
