version: '3.3'

services:
    zigbee2mqtt:
      image: koenkk/zigbee2mqtt:latest
      volumes:
        - /path/to/home_dir:/app/data
      restart: always
      devices:
        - /path/to/device:/dev/zigbee
      logging:
        driver: "json-file"
        options:
          max-file: "2"
          max-size: "100m"

