version: '3.3'

services:
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:latest
    container_name: zigbee2mqtt
    volumes:
      - ${DATA_DIR}:/app/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: 'Europe/Paris'
    restart: always
    devices:
      - ${DEVICE_DIR}:/dev/zigbee
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "100m"
    network_mode: "bridge"
    ports:
      - "${PORT}:8080"